from fpdf import FPDF
from datetime import datetime
import os
import re
from typing import Dict, Any, List

class PDFService:
    def create_lecture_notes(self, data: Dict[str, Any], output_path: str):
        """
        Generate structured PDF notes from AI analysis.
        """
        print(f"DEBUG: Generating PDF with keys: {list(data.keys())}")
        
        # Sanitize all data
        data = self._sanitize_data(data)
        
        # Configure PDF with proper margins to prevent layout errors
        pdf = FPDF(format='A4')  # Explicitly set A4 format
        pdf.set_auto_page_break(auto=True, margin=15)
        pdf.set_margins(left=20, top=20, right=20)
        pdf.add_page()
        
        # Header
        pdf.set_font("Helvetica", "B", 20)
        pdf.set_text_color(44, 62, 80) # Dark Blue
        pdf.cell(0, 15, data.get("title", "Lecture Notes"), ln=True, align="C")
        
        pdf.set_font("Helvetica", "I", 10)
        pdf.cell(0, 5, f"Generated by MentorAI on {datetime.now().strftime('%Y-%m-%d %H:%M')}", ln=True, align="C")
        pdf.ln(10)
        
        # Sanitize all data
        data = self._sanitize_data(data)
        
        # Summary Section
        self._add_section(pdf, "Executive Summary", data.get("summary", "No summary provided."))
        
        # Topic Breakdown
        if data.get("topics"):
            self._add_list_section(pdf, "Topic Breakdown", data["topics"])
            
        # Key Concepts
        if data.get("concepts"):
            self._add_list_section(pdf, "Key Concepts", data["concepts"])
        
        # Formulas & Equations (NEW!)
        if data.get("formulas"):
            self._add_list_section(pdf, "Formulas & Equations", data["formulas"])
            
        # Definitions
        if data.get("definitions"):
            self._add_dict_section(pdf, "Glossary & Definitions", data["definitions"])
            
        # Examples
        if data.get("examples"):
            self._add_list_section(pdf, "Examples Mentioned", data["examples"])
            
        # Footer
        pdf.set_y(-25)
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(149, 165, 166)
        pdf.cell(0, 10, "Note: These notes were automatically generated from lecture audio.", align="C")
        
        pdf.output(output_path)
        return output_path

    def _add_section(self, pdf, title, content):
        pdf.set_font("Helvetica", "B", 14)
        pdf.set_text_color(52, 73, 94)
        pdf.cell(0, 10, title, ln=True)
        pdf.set_font("Helvetica", "", 11)
        pdf.set_text_color(0, 0, 0)
        try:
            # Truncate very long content to prevent layout issues
            if len(content) > 5000:
                content = content[:5000] + "... [truncated]"
            pdf.multi_cell(0, 7, content)
        except Exception as e:
            print(f"PDF Rendering Error in section '{title}': {e}")
            pdf.cell(0, 7, "[Content rendering error]", ln=True)
        pdf.ln(5)

    def _add_list_section(self, pdf, title, items):
        pdf.set_font("Helvetica", "B", 14)
        pdf.set_text_color(52, 73, 94)
        pdf.cell(0, 10, title, ln=True)
        pdf.set_font("Helvetica", "", 11)
        pdf.set_text_color(0, 0, 0)
        for item in items:
            try:
                item_text = str(item)[:500]  # Limit item length
                pdf.multi_cell(0, 7, f"- {item_text}")
            except Exception as e:
                print(f"PDF Rendering Error for list item: {e}")
                pdf.cell(0, 7, "- [Item rendering error]", ln=True)
        pdf.ln(5)

    def _add_dict_section(self, pdf, title, items):
        pdf.set_font("Helvetica", "B", 14)
        pdf.set_text_color(52, 73, 94)
        pdf.cell(0, 10, title, ln=True)
        pdf.set_font("Helvetica", "", 11)
        pdf.set_text_color(0, 0, 0)
        for term, definition in items.items():
            pdf.set_font("Helvetica", "B", 11)
            pdf.write(7, f"{term}: ")
            pdf.set_font("Helvetica", "", 11)
            pdf.write(7, f"{definition}\n")
        pdf.ln(5)

    def _clean_text(self, text: str) -> str:
        """Nuclear Option: Strip ALL non-ASCII characters to save PDF generation."""
        if not isinstance(text, str):
            return str(text)
        
        # 1. Common character mapping
        replacements = {
            "\u2022": "-", "\u2013": "-", "\u2014": "--",
            "\u2018": "'", "\u2019": "'", "\u201c": '"', "\u201d": '"',
            "\u2026": "..."
        }
        for old, new in replacements.items():
            text = text.replace(old, new)
        
        # 2. Regex to remove ANY remaining non-ASCII character
        # This prevents the "Character \uXXXX is outside the range" error
        return re.sub(r'[^\x00-\x7f]', r'', text)

    def _sanitize_data(self, data: Dict[str, Any]) -> Dict[str, Any]:
        """Deeply sanitize dictionaries and lists for PDF safety."""
        if isinstance(data, str):
            return self._clean_text(data)
        if isinstance(data, list):
            return [self._sanitize_data(item) for item in data]
        if isinstance(data, dict):
            return {self._clean_text(k): self._sanitize_data(v) for k, v in data.items()}
        return data

pdf_service = PDFService()
